myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.homepage),
    path('about/',views.aboutpage),
    path('posts/', include('posts.urls'))
]

myproject/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.posts_list,name="list"),
     path('<slug:slug>/', views.post_page,name="post_page"),
]

myproject/posts/models.py
from django.db import models

# Create your models here.

class Post(models.Model):
    title= models.CharField(max_length=75)
    body = models.TextField()
    slug = models.SlugField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

myproject/myproject/views.py
#from django.http import HttpResponse
from django.shortcuts import render

def homepage(request):
 #  return HttpResponse("Welcome to the Homepage!")
  return render(request,'home.html')

def aboutpage(request):
 #   return HttpResponse("This is the About Page.")
   return render(request,'about.html')

myproject/posts/views.py
from django.shortcuts import render
from .models import Post



def posts_list(request):
    posts = Post.objects.all().order_by('-date')
    return render(request,'posts/posts_list.html', {'posts': posts})
# Create your views here.

def post_page(request, slug):
     post = Post.objects.get(slug=slug)
     return render(request, 'posts/post_page.html', {'post': post})

   

myproject/posts/templates/posts/post_page.html
{% extends 'layout.html'%}

{% block title %}
{{ post.title }}
 {% endblock  %}

 {% block content %}
 <section>
    <h1>{{ post.title }}</h1>
   
      <p>{{post.title}}</p>
    <p>Published on: {{ post.date }}</p>
     <p>{{ post.body }}</p>
   
        
   
  </section>

  {% endblock  %}

myproject/posts/templates/posts/posts_list.html
{% extends 'layout.html'%}

{% block title %}
Posts
 {% endblock  %}

 {% block content %}
 <section>
    <h1>Post List</h1>
    {% for post in posts %}
        <article>
            <h2>
                <a href="{% url 'posts:post_page' slug=post.slug %}">


                {{ post.title }}
                </a>
        </h2>
            <p>{{ post.body }}</p>
            <p>Published on: {{ post.date }}</p>
        </article>
    {% endfor %}
  </section>

  {% endblock  %}

myproject/templates/about.html
{% extends 'layout.html'%}

{% block title %}
 About
 {% endblock  %}

 {% block content %}
<h1>About Page</h1>
<p> check out my <a href="/">home </a> </p>
  {% endblock  %}

myproject/templates/home.html
{% extends 'layout.html'%}

{% block title %}
 Home
 {% endblock  %}

 {% block content %}
<h1>Home</h1>
<p> check out my <a href="/about">about page</a> </p>
  {% endblock  %}

myproject/templates/layout.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
           Django App
        {% endblock title %}
    </title>
    <script src="{% static 'js/main.js'%}"></script>
   <link rel="stylesheet" href="{% static 'css/style.css'%}?v=123">

</head>

<body>
   <nav>
         <a href="/">Home</a> |
         <a href="/about">About</a> |
         <a href="{% url 'posts:list' %}">Posts</a>
   </nav>
   <main>
        {% block content %}
        {% endblock content %}
   </main>
</body>

</html>